export const API_KEY = '1ZRFEVRVI8IDMUAD';
export const COMPANY_DETAILS = 'Company details';
export const TECHNICAL = 'Technical';
export const FUNDAMENTAL = 'Fundamental';
export const DELETE_COMPANY = 'Delete company';
export const FAIL_ADD_NEW_COMPANY = 'Fail to add a new company';
export const FETCH_COMPANY_OVERVIEW_FULFILLED = '/stocks/info/fetchCompanyData/fulfilled';
export const FETCH_COMPANY_OVERVIEW_PENDING = '/stocks/info/fetchCompanyData/pending';
export const FETCH_COMPANY_OVERVIEW_REJECTED = '/stocks/info/fetchCompanyData/rejected';
export const MY_COMPANIES = 'My companies';
export const SUCCESS = 'Success';
export const NAME_COMPANY_INPUT = 'Input company name'
